services:
  postgres:
    image: postgres
    restart: always
    container_name: teklif-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: teklif-backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: teklif-frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:
